/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 MIT_Driverless_Model.glb 
*/

import {useGLTF} from "@react-three/drei";
import {useFrame} from "@react-three/fiber";
import React from "react";

export default function AV21(props) {
    const {nodes, materials} = useGLTF("models/MIT_Driverless_Model.glb");

    const wheel_1 = React.useRef();
    const wheel_2 = React.useRef();
    const wheel_3 = React.useRef();
    const wheel_4 = React.useRef();

    useFrame(({clock}) => {
        if (props.isMoving) {
            let new_rotation = clock.getElapsedTime() * (props.movementSpeed || 2);
            if (wheel_1.current) {
                wheel_1.current.rotation.x = new_rotation;
            }
            if (wheel_2.current) {
                wheel_2.current.rotation.x = new_rotation;
            }
            if (wheel_3.current) {
                wheel_3.current.rotation.x = new_rotation;
            }
            if (wheel_4.current) {
                wheel_4.current.rotation.x = new_rotation;
            }
        }
    });

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Circle003.geometry}
                material={materials["MIT Metal"]}
                position={[2.334, 0.907, -3.475]}
                scale={[0.184, 0.122, 0.122]}
                ref={wheel_1}
            />
            <mesh
                geometry={nodes.Circle004.geometry}
                material={materials["MIT Metal"]}
                position={[2.522, 0.907, 4.856]}
                scale={[0.184, 0.122, 0.122]}
                ref={wheel_2}
            />
            <mesh
                geometry={nodes.Circle007.geometry}
                material={materials["MIT Metal"]}
                position={[-2.526, 0.907, 4.856]}
                rotation={[Math.PI, 0, Math.PI]}
                scale={[0.184, 0.122, 0.122]}
                ref={wheel_3}
            />
            <mesh
                geometry={nodes.Circle009.geometry}
                material={materials["MIT Metal"]}
                position={[-2.387, 0.907, -3.475]}
                rotation={[Math.PI, 0, Math.PI]}
                scale={[0.184, 0.122, 0.122]}
                ref={wheel_4}
            />

            <group>
                <group position={[2.246, 0.907, 4.856]} scale={[0.783, 1.034, 0.686]}>
                    <mesh geometry={nodes.Circle006_1.geometry} material={materials["MIT Dark"]} />
                    <mesh geometry={nodes.Circle006_2.geometry} material={materials["MIT Metal"]} />
                </group>
                <group position={[1.999, 0.907, -3.475]} scale={[0.686, 1.034, 0.686]}>
                    <mesh geometry={nodes.Circle010_1.geometry} material={materials["MIT Dark"]} />
                    <mesh geometry={nodes.Circle010_2.geometry} material={materials["MIT Metal"]} />
                </group>
                <group position={[-2.25, 0.907, 4.856]} rotation={[Math.PI, 0, Math.PI]} scale={[0.783, 1.034, 0.686]}>
                    <mesh geometry={nodes.Circle012.geometry} material={materials["MIT Dark"]} />
                    <mesh geometry={nodes.Circle012_1.geometry} material={materials["MIT Metal"]} />
                </group>
                <group
                    position={[-2.051, 0.907, -3.475]}
                    rotation={[Math.PI, 0, Math.PI]}
                    scale={[0.686, 1.034, 0.686]}
                >
                    <mesh geometry={nodes.Circle014.geometry} material={materials["MIT Dark"]} />
                    <mesh geometry={nodes.Circle014_1.geometry} material={materials["MIT Metal"]} />
                </group>
            </group>

            <mesh
                geometry={nodes.Cylinder020.geometry}
                material={materials["Cradle Metal"]}
                position={[0, 0.89, -3.459]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.152, 1.979, 0.152]}
            />
            <mesh
                geometry={nodes.Cylinder021.geometry}
                material={materials["MIT Metal"]}
                position={[0, 0.89, 4.845]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.131, 1.979, 0.131]}
            />
            <mesh
                geometry={nodes.Cylinder022.geometry}
                material={materials["MIT Dark"]}
                position={[0, 2.522, 1.934]}
                scale={0.464}
            />
            <mesh
                geometry={nodes.Cylinder023.geometry}
                material={materials["MIT Dark"]}
                position={[0, 2.73, 1.827]}
                rotation={[0, 0, Math.PI / 2]}
                scale={[0.609, 2.145, 0.609]}
            />
            <mesh
                geometry={nodes.Cylinder024.geometry}
                material={materials["MIT Dark"]}
                position={[0, 1.654, -0.755]}
                rotation={[0.577, 0, 0]}
                scale={[0.032, 0.221, 0.032]}
            />
            <group position={[0, 0.106, 1.412]}>
                <mesh geometry={nodes.Plane120.geometry} material={materials["MIT Base"]} />
                <mesh geometry={nodes.Plane120_1.geometry} material={materials["MIT Dark"]} />
            </group>
            <group position={[0, 0.144, -6.159]} scale={[1, 1, 0.448]}>
                <mesh geometry={nodes.Plane121.geometry} material={materials["MIT Base"]} />
                <mesh geometry={nodes.Plane121_1.geometry} material={materials["MIT Dark"]} />
            </group>
            <mesh geometry={nodes.Plane045.geometry} material={materials["MIT Dark"]} position={[0, 0.106, 1.134]} />
            <group position={[0, 1.834, 6.482]} scale={[1.958, 1, 0.694]}>
                <mesh geometry={nodes.Plane123.geometry} material={materials["MIT Base"]} />
                <mesh geometry={nodes.Plane123_1.geometry} material={materials["MIT Dark"]} />
            </group>
            <mesh
                geometry={nodes.Plane047.geometry}
                material={materials["MIT Dark"]}
                position={[0, 2.228, 2.024]}
                scale={[1, 1, 0.532]}
            />
            <mesh
                geometry={nodes.Plane048.geometry}
                material={materials["MIT Dark"]}
                position={[0, 2.186, 0.637]}
                scale={[0.811, 1, 1]}
            />
            <mesh geometry={nodes.Plane049.geometry} material={materials["MIT Dark"]} position={[0, 3.179, 1.17]} />
        </group>
    );
}

useGLTF.preload("models/MIT_Driverless_Model.glb");
