/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 static/models/Lever_Handle.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Lever_Handle(props) {
  const { nodes, materials } = useGLTF('models/Lever_Handle-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Lever Shaft']} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} position={[0, -7, 0]} rotation={[Math.PI / 2, 0, 0]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('models/Lever_Handle-transformed.glb')
