/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 static/models/Shoe.glb -T
*/

import {useGLTF, useScroll} from "@react-three/drei";
import {useFrame} from "@react-three/fiber";
import React from "react";

export default function Shoe(props) {
    const {nodes, materials} = useGLTF("models/Shoe-transformed.glb");
    const scroll = useScroll();

    useFrame((state, delta) => {
        // The offset is between 0 and 1, you can apply it to your models any way you like
        const offset = 1 - scroll.offset;
        // action.time = THREE.MathUtils.damp(action.time, (action.getClip().duration / 2) * offset, 100, delta)
        state.camera.position.set(
            Math.sin(offset) * -10,
            Math.atan(offset * Math.PI * 2) * 5,
            Math.cos((offset * Math.PI) / 3) * -10
        );
        state.camera.lookAt(0, 0, 0);
    });
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Shoe_V4_Side.geometry} material={nodes.Shoe_V4_Side.material}>
                <mesh
                    geometry={nodes.Shoe_Rings.geometry}
                    material={materials["Shoe Base Colour"]}
                    position={[0, 0.29, 0]}
                    scale={0.05}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Back_Leather.geometry}
                    material={materials["Shoe Accent Colour"]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Back_Leather_Stitch.geometry}
                    material={nodes.Shoe_V4_Back_Leather_Stitch.material}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Front.geometry}
                    material={materials["Shoe Base Colour"]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Lace_Leathers.geometry}
                    material={materials["Shoe Accent Colour"]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Lace_Leathers_Stitch.geometry}
                    material={nodes.Shoe_V4_Lace_Leathers_Stitch.material}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh geometry={nodes.Shoe_V4_Laces.geometry} material={materials["Shoe Accent Colour 2"]} />
                <mesh
                    geometry={nodes.Shoe_V4_Loop.geometry}
                    material={nodes.Shoe_V4_Loop.material}
                    position={[2.44, 0.56, 0]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.19}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Loop_Stitch.geometry}
                    material={nodes.Shoe_V4_Loop_Stitch.material}
                    position={[2.44, 0.56, 0]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.19}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Soul.geometry}
                    material={materials["Shoe Base Colour"]}
                    position={[0, 0.06, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Soul_Back.geometry}
                    material={materials["Shoe Accent Colour"]}
                    position={[0, 0.06, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Soul_Front.geometry}
                    material={materials["Shoe Accent Colour"]}
                    position={[0, 0.06, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Toe.geometry}
                    material={materials["Shoe Accent Colour"]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Toe_Stitch.geometry}
                    material={nodes.Shoe_V4_Toe_Stitch.material}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Toe_Wrap.geometry}
                    material={materials["Shoe Accent Colour"]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Toe_Wrap_Stitch.geometry}
                    material={nodes.Shoe_V4_Toe_Wrap_Stitch.material}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Top.geometry}
                    material={materials["Shoe Accent Colour"]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Toungue_Top.geometry}
                    material={materials["Shoe Accent Colour"]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Shoe_V4_Treads.geometry}
                    material={materials["Shoe Base Colour"]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
            </mesh>
        </group>
    );
}

useGLTF.preload("models/Shoe-transformed.glb");
